name: LoupGagrou
main: com.lougagrou.LoupGagrouPlugin
version: 1.0
api-version: 1.21
commands:
  startgame:
    description: Démarrer une partie
    usage: /startgame
  role:
    description: Afficher ton rôle
    usage: /role